# Compose file to use tensorflow with gpu and local files
version: "3.8"

services:
  tensorflow:
    container_name: tensor_gpu
    ports:
        - '8888:8888'
    volumes:
        - '/home/luis/Documents/personal_projects/tensor_flow_gpu/docker_mount:/tf/notebooks'
    image: tensor_gpu_image:dev
    command: bash
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    user: "${UID}:${GID}" # -u $(id -u):$(id -g) must run
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]