version: "3.8"

services:
  test:
    image: tensorflow/tensorflow:latest-gpu-jupyter
    command: python -c "import tensorflow as tf;tf.test.gpu_device_name()"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
